function options = define_options()

	tols = 1e-5;
	options = optimset('Algorithm','levenberg-marquardt',...
		'Display','off',...
		'MaxFunEvals',10000,...
		'MaxIter',10000,...
		'TolX',tols,...
		'TolFun',tols,...
		'TolCon',tols ,...
		'UseParallel','always');
end